### PR TITLE
NXDN add

### PR DESCRIPTION
**Pull request by vk4tux**
...

### CODE REVIEW

**Comment by vk4tux** [comment]
NXDN.csv confirmed, no reference needed.

**Review by phl0 — CHANGES_REQUESTED** [review]
I suggest to restore the blank lines. It helps keeping the source readable.

**Comment by phl0** [comment]
I cherry-picked two commits and will rework the blank line issue while merging.

**Comment by phl0** [comment]
As stated: I edited the commit and removed all blank line deletions. It is now upstream as https://github.com/dg9vh/MMDVMHost-Dashboard/commit/5bf0644c77a8f79c59df14ce582bc130e5d43692

**Pull request closed without merging**
