### PR TITLE
Embedded Data with Slot number

### PR DESCRIPTION
**Pull request by pjao**
Fixing https://github.com/dg9vh/MMDVMHost-Dashboard/pull/104

Lets wait for https://github.com/g4klx/MMDVMHost/issues/268

### CODE REVIEW

**Comment by dg9vh** [comment]
Are prerequired conditions given? Lost focus on this.

**Comment by pjao** [comment]
Nop. Not yet, do you prefer close and reopen or make another PR after pre required condition satisfied?

**Comment by pjao** [comment]
@dg9vh,

Jonathan, @g4klx,  just closed my "Feature Request - DMR - Embedded Data with Slot number " https://github.com/g4klx/MMDVMHost/issues/268

@phl0 do you still working on this?

@dg9vh What's you think about?

**Comment by dg9vh** [comment]
@pjao I think, we keep this open until situation is clear if the PR at Jonathans repo would be accepted or not... if not, we can close this, if, we commit it :-)
@phl0 could you say something about the status in Jonathans repo?

**Comment by dg9vh** [comment]
With latest information I think we close this PR and wait for better seasons...

**Comment by pjao** [comment]
Thanks @dg9vh for your support,

I'll keep a branch (dumpDMR) on MMDVMHost and MMDVMHost-Dashboard as long it's possible with this function working since it's in use on several homebrew repeaters on Portugal.

**Pull request closed without merging**
