### PR TITLE
Fixed TalkerAlias - Embedded Data with Slot number

### PR DESCRIPTION
**Pull request by pjao**
@dg9vh please see https://github.com/g4klx/MMDVMHost/issues/268

After @g4klx accept it, you could also accept this one!

Also changed the version.

### CODE REVIEW

**Comment by pjao** [comment]
Also included a fix to one of my lasts PR that it give and error on syslog:

Mar  9 01:18:57 CT2JAY-MMDVM lighttpd[8667]: grep: from|end|watchdog|lost|Alias|0000: No such file or directory

Fixing egrep command
- Two _**and**_ expressions with grep you need two invocations 
- No need also to use egrep again, grep it's ok

**Comment by dg9vh** [comment]
Could you give me a note here, if it is committed by Jonathan? I am vy busy at the moment and could not monitor him...

**Comment by phl0** [comment]
I can do that. I need to analyze a possible regression for log level 1 before I can PR that to MMDVMHost.

**Comment by dg9vh** [comment]
@phl0 FileLevel = 1 is not recommended due to big logfiles and a great amount of time to process them. The logs would grow very fast to 30 or 40 Megabytes that is not ok for processing via PHP and so on. Therefore we prefer FileLevel = 2.

**Comment by phl0** [comment]
Yes I know. But if my change to the code makes problems if the log level is set to 1 I must correct that. I do not want to make log level 1 useless though it is not used for the dashboard.

**Comment by dg9vh** [comment]
@phl0 cfm, now I understood :-)

**Comment by pjao** [comment]
Closing... Let's wait.

**Pull request closed without merging**
