### PR TITLE
Filter useless -0/-0/-0 dBm values (missing RSSI)

### PR DESCRIPTION
**Pull request by phl0**
DVmega gives "-0/-0/-0 dBm" in the log. That is useless and should be suppressed in the Dashboard output.

### CODE REVIEW

**Comment by pjao** [comment]
Hi there! 

On dvmega it appears the text "false" 


screenshot_20170108-115117_1

**Comment by phl0** [comment]
Upz. Which version of my branch is that?

**Comment by phl0** [comment]
Could you please quote the corresponding lines from the MMDVMHost log?

**Comment by pjao** [comment]
It seams that in case of dvmega is not putting any more the  "-0/-0/-0 dBm" in the log.

M: 2017-01-08 15:37:30.951 DMR Slot 2, received RF voice header from CT2JAY to 9990
D: 2017-01-08 15:37:31.130 DMR Slot 2, audio sequence no. 0, errs: 0/141
D: 2017-01-08 15:37:31.188 DMR Slot 2, audio sequence no. 1, errs: 0/141
D: 2017-01-08 15:37:31.248 DMR Slot 2, audio sequence no. 2, errs: 0/141
D: 2017-01-08 15:37:31.308 DMR Slot 2, audio sequence no. 3, errs: 0/141
D: 2017-01-08 15:37:31.371 DMR Slot 2, audio sequence no. 4, errs: 0/141
D: 2017-01-08 15:37:31.429 DMR Slot 2, audio sequence no. 5, errs: 5/141
D: 2017-01-08 15:37:31.494 DMR Slot 2, audio sequence no. 0, errs: 3/141
D: 2017-01-08 15:37:31.548 DMR Slot 2, audio sequence no. 1, errs: 0/141
D: 2017-01-08 15:37:31.608 DMR Slot 2, audio sequence no. 2, errs: 1/141
D: 2017-01-08 15:37:31.673 DMR Slot 2, audio sequence no. 3, errs: 2/141
D: 2017-01-08 15:37:31.731 DMR Slot 2, audio sequence no. 4, errs: 1/141
D: 2017-01-08 15:37:31.789 DMR Slot 2, audio sequence no. 5, errs: 1/141
D: 2017-01-08 15:37:31.848 DMR Slot 2, audio sequence no. 0, errs: 4/141
D: 2017-01-08 15:37:31.908 DMR Slot 2, audio sequence no. 1, errs: 1/141
D: 2017-01-08 15:37:31.968 DMR Slot 2, audio sequence no. 2, errs: 0/141
D: 2017-01-08 15:37:32.030 DMR Slot 2, audio sequence no. 3, errs: 0/141
D: 2017-01-08 15:37:32.088 DMR Slot 2, audio sequence no. 4, errs: 1/141
D: 2017-01-08 15:37:32.151 DMR Slot 2, audio sequence no. 5, errs: 1/141
D: 2017-01-08 15:37:32.208 DMR Slot 2, audio sequence no. 0, errs: 1/141
D: 2017-01-08 15:37:32.270 DMR Slot 2, audio sequence no. 1, errs: 0/141
D: 2017-01-08 15:37:32.328 DMR Slot 2, audio sequence no. 2, errs: 0/141
D: 2017-01-08 15:37:32.391 DMR Slot 2, audio sequence no. 3, errs: 0/141
D: 2017-01-08 15:37:32.449 DMR Slot 2, audio sequence no. 4, errs: 1/141
D: 2017-01-08 15:37:32.648 DMR Slot 2, audio sequence no. 5, errs: 0/141
D: 2017-01-08 15:37:32.653 DMR Slot 2, audio sequence no. 0, errs: 0/141
D: 2017-01-08 15:37:32.654 DMR Slot 2, audio sequence no. 1, errs: 0/141
D: 2017-01-08 15:37:32.693 DMR Slot 2, audio sequence no. 2, errs: 1/141
D: 2017-01-08 15:37:32.751 DMR Slot 2, audio sequence no. 3, errs: 0/141
D: 2017-01-08 15:37:32.810 DMR Slot 2, audio sequence no. 4, errs: 0/141
D: 2017-01-08 15:37:32.868 DMR Slot 2, audio sequence no. 5, errs: 1/141
D: 2017-01-08 15:37:32.928 DMR Slot 2, audio sequence no. 0, errs: 1/141
D: 2017-01-08 15:37:32.993 DMR Slot 2, audio sequence no. 1, errs: 1/141
D: 2017-01-08 15:37:33.051 DMR Slot 2, audio sequence no. 2, errs: 1/141
D: 2017-01-08 15:37:33.108 DMR Slot 2, audio sequence no. 3, errs: 0/141
D: 2017-01-08 15:37:33.171 DMR Slot 2, audio sequence no. 4, errs: 4/141
D: 2017-01-08 15:37:33.228 DMR Slot 2, audio sequence no. 5, errs: 1/141
D: 2017-01-08 15:37:33.291 DMR Slot 2, audio sequence no. 0, errs: 0/141
D: 2017-01-08 15:37:33.348 DMR Slot 2, audio sequence no. 1, errs: 0/141
D: 2017-01-08 15:37:33.411 DMR Slot 2, audio sequence no. 2, errs: 0/141
D: 2017-01-08 15:37:33.469 DMR Slot 2, audio sequence no. 3, errs: 9/141
D: 2017-01-08 15:37:33.528 DMR Slot 2, audio sequence no. 4, errs: 1/141
D: 2017-01-08 15:37:33.591 DMR Slot 2, audio sequence no. 5, errs: 0/141
D: 2017-01-08 15:37:33.648 DMR Slot 2, audio sequence no. 0, errs: 0/141
D: 2017-01-08 15:37:33.708 DMR Slot 2, audio sequence no. 1, errs: 0/141
D: 2017-01-08 15:37:33.771 DMR Slot 2, audio sequence no. 2, errs: 1/141
D: 2017-01-08 15:37:33.829 DMR Slot 2, audio sequence no. 3, errs: 0/141
D: 2017-01-08 15:37:33.888 DMR Slot 2, audio sequence no. 4, errs: 4/141
D: 2017-01-08 15:37:33.951 DMR Slot 2, audio sequence no. 5, errs: 3/141
D: 2017-01-08 15:37:34.008 DMR Slot 2, audio sequence no. 0, errs: 3/141
D: 2017-01-08 15:37:34.068 DMR Slot 2, audio sequence no. 1, errs: 1/141
D: 2017-01-08 15:37:34.128 DMR Slot 2, audio sequence no. 2, errs: 0/141
D: 2017-01-08 15:37:34.188 DMR Slot 2, audio sequence no. 3, errs: 0/141
D: 2017-01-08 15:37:34.250 DMR Slot 2, audio sequence no. 4, errs: 0/141
D: 2017-01-08 15:37:34.308 DMR Slot 2, audio sequence no. 5, errs: 1/141
M: 2017-01-08 15:37:34.370 DMR Slot 2, received RF end of voice transmission, 3.2 seconds, BER: 0.7%
M: 2017-01-08 15:37:37.631 DMR Slot 2, received network voice header from 9990 to CT2JAY

**Pull request merged**
