### PR TITLE
DMRIDs data from database of the BM network

### PR DESCRIPTION
**Pull request by s-s-s**
To get the data from database of the BrandMeister network in right format

### CODE REVIEW

**Comment by pjao** [comment]
Is that really needed? You can use the file on MMDVMHost and MMDVMHost-Dashboard from the command:

curl 'http://registry.dstar.su/dmr/DMRIds.php' 2>/dev/null > ${DMRIDFILE}

**Comment by s-s-s** [comment]
This command (curl 'http://registry.dstar.su/dmr/DMRIds.php' 2>/dev/null > ${DMRIDFILE} ) creates a file with incorrect formatting, to which for example the dashboard in the name field writes an error.
There are other applications that do not like this format, which contains tabs and blanks

**Comment by pjao** [comment]
@s-s-s all right with me... since is already merged with MMDVMHost.

Could I suggest a change, one line only?

curl 'http://registry.dstar.su/dmr/DMRIds.php' 2>/dev/null |  sed -e 's/ /\t\t/g' | sed -e 's/\t/ /g' | sed -e 's/  / /g' > ${DMRIDFILE}

**Comment by dg9vh** [comment]
now it is merged, you can push your change on it...

**Comment by pjao** [comment]
@dg9vh, lets see what @s-s-s says on MMDVMHost. Dammm copy&paste. 

This way it will looks nicer :) 

curl 'http://registry.dstar.su/dmr/DMRIds.php' 2>/dev/null | sed -e 's/[[:space:]]\\+/ /g' > ${DMRIDFILE}

**Comment by s-s-s** [comment]
Exellent! It works well.

**Comment by pjao** [comment]
@s-s-s make the pull request on MMDVMHost and MMDVMHost-Dashboard!

**Pull request merged**
