### PR TITLE
Add RSSI support

### PR DESCRIPTION
**Pull request by phl0**
Add column to display the RSSI data gathered from local transmissions.

### CODE REVIEW

**Comment by ernix66** [comment]
Works fine. Q

**Comment by iw9grl** [comment]
Thank you !!!!!!!!!!!!!!!!

**Comment by dg9vh** [comment]
Ist this tested with non-enabled rssi-logging? I mean with standard logs of DVMEGA for example? If not working with them, it should be configured with setup.php

**Comment by phl0** [comment]
Good idea. I haven't tested it with non-RSSI logging. I need to do that
and possibly fix my code then :-)

**Comment by phl0** [comment]
Tests with DVmega done. Logs just says 0dBm as reported RSSI. Dashboard works fine.

bildschirmfoto vom 2017-01-08 00-04-37

**Pull request merged**
